### ISSUE TITLE
can not import NewAttributes() function

### ISSUE THREAD

**Issue by hitpopo** [ultimate-guitar/go-imagequant#5]
![Screenshot 2020-06-26 at 6 44 24 PM](https://user-images.githubusercontent.com/51782758/85849181-0fdcb780-b7dd-11ea-8488-d32dd51f86a8.png)

my project want to use this pngquant method, and I import the package like the following picture
![Screenshot 2020-06-26 at 6 45 38 PM](https://user-images.githubusercontent.com/51782758/85849266-3d296580-b7dd-11ea-874e-87d37a73f829.png)

use the function in this way
![Screenshot 2020-06-26 at 6 46 15 PM](https://user-images.githubusercontent.com/51782758/85849312-53372600-b7dd-11ea-97cc-469da06b13a1.png)

when I compile my project, I faced the issue in the first picture, seems like a compile problem, 
![Screenshot 2020-06-26 at 6 49 44 PM](https://user-images.githubusercontent.com/51782758/85849586-ce98d780-b7dd-11ea-869b-fb4b51bec88d.png)

this is my gcc version, I am not familiar with c, so anyone can help me to solve this issue?

**Comment by larrabee** [comment]
Hello.  
Try to download the package with `go get -u github.com/ultimate-guitar/go-imagequant`

**Comment by hitpopo** [comment]
Thanks for replying,
I did download this package in this way `go get -u github.com/ultimate-guitar/go-imagequant`

**Comment by larrabee** [comment]
Can you cd to `~$GOPATH/src/github.com/ultimate-guitar/go-imagequant` and run `go build`?

**Comment by hitpopo** [comment]
I executed `go build` but still get the error

**Comment by larrabee** [comment]
What go version are you use?

**Comment by hitpopo** [comment]
`go version go1.13.3 linux/amd64`

**Comment by larrabee** [comment]
It look's like you have not all files. Try to remove the package from `src/` and `pkg/` folders and try to install it.
You also can clone the repo and try to build it to check that it's build fine.

**Comment by hitpopo** [comment]
I finally found the problem, for I was using CGO_ENABLED=0 to do the compile. If I don't use this env parameter, everything goes well, thanks, Iarrabee.
